package org.thoughtcrime.securesms.jobs

import org.signal.core.models.ServiceId
import org.signal.core.util.logging.Log
import org.thoughtcrime.securesms.database.GroupTable
import org.thoughtcrime.securesms.database.SignalDatabase
import org.thoughtcrime.securesms.database.documents.NetworkFailure
import org.thoughtcrime.securesms.database.model.RecipientRecord
import org.thoughtcrime.securesms.database.participantdelete.ParticipantDeleteConfig
import org.thoughtcrime.securesms.dependencies.AppDependencies
import org.thoughtcrime.securesms.jobmanager.Job
import org.thoughtcrime.securesms.jobmanager.impl.NetworkConstraint
import org.thoughtcrime.securesms.jobmanager.impl.SealedSenderConstraint
import org.thoughtcrime.securesms.jobs.protos.ParticipantDeleteSendJobData
import org.thoughtcrime.securesms.keyvalue.SignalStore
import org.thoughtcrime.securesms.messages.GroupSendUtil
import org.thoughtcrime.securesms.recipients.Recipient
import org.thoughtcrime.securesms.recipients.RecipientId
import org.thoughtcrime.securesms.recipients.RecipientUtil
import org.thoughtcrime.securesms.util.GroupUtil
import org.whispersystems.signalservice.api.crypto.ContentHint
import org.whispersystems.signalservice.api.messages.SignalServiceDataMessage
import org.whispersystems.signalservice.api.messages.SignalServiceDataMessage.Companion.newBuilder
import kotlin.time.Duration.Companion.days

/**
 * Job that fans out a user-initiated ParticipantDelete proto message to every conversation member.
 *
 * Unlike [AdminDeleteSendJob], this supports BOTH direct-chat (scope=DIRECT_CHAT_BOTH_ACCOUNTS)
 * and group-v2 (scope=GROUP_ALL_CURRENT_MEMBERS) contexts, because participant-delete is a
 * cooperative protocol open to ANY current member — not just admins.
 *
 * A companion [OutgoingParticipantDeleteReceiptJob] is sent by each member after they apply the
 * delete; this Job is only responsible for delivering the initial delete request.
 */
class ParticipantDeleteSendJob private constructor(
  private val messageId: Long,
  private val requestId: ByteArray,
  private val recipientIds: MutableList<Long>,
  private val initialRecipientCount: Int,
  parameters: Parameters
) : Job(parameters) {

  companion object {
    const val KEY: String = "ParticipantDeleteSendJob"
    private val TAG = Log.tag(ParticipantDeleteSendJob::class.java)

    /**
     * Create a Job for a user-initiated participant delete.
     *
     * @param messageId  Row ID of the message being deleted.
     * @param requestId  16-byte UUID that uniquely identifies this delete request (generated by
     *                   the caller *before* enqueueing — the Manager needs it to write its rows).
     */
    @JvmStatic
    fun create(messageId: Long, requestId: ByteArray): ParticipantDeleteSendJob? {
      if (!SignalStore.account.isRegistered) {
        Log.w(TAG, "Not registered. Cannot create participant-delete job.")
        return null
      }

      val message = SignalDatabase.messages.getMessageRecordOrNull(messageId)
      if (message == null) {
        Log.w(TAG, "Message not found for id=$messageId")
        return null
      }

      val conversationRecipientId = SignalDatabase.threads.getRecipientIdForThreadId(message.threadId)
      if (conversationRecipientId == null) {
        Log.w(TAG, "Thread recipient not found for threadId=${message.threadId}")
        return null
      }

      val conversationRecipient = SignalDatabase.recipients.getRecord(conversationRecipientId)
      val groupId = conversationRecipient.groupId

      val recipientIds: List<Long> = if (groupId != null && groupId.isV2) {
        // Group v2: fan out to ALL members
        SignalDatabase.groups
          .getGroupMemberIds(groupId, GroupTable.MemberSet.FULL_MEMBERS_INCLUDING_SELF)
          .map { it.toLong() }
      } else {
        // Direct chat: fan out to the peer only (not self — self is handled via sendSyncMessage)
        listOf(conversationRecipient.id.toLong())
      }

      return ParticipantDeleteSendJob(
        messageId = messageId,
        requestId = requestId,
        recipientIds = recipientIds.toMutableList(),
        initialRecipientCount = recipientIds.size,
        parameters = Parameters.Builder()
          .setQueue(conversationRecipient.id.toQueueKey())
          .addConstraint(NetworkConstraint.KEY)
          .addConstraint(SealedSenderConstraint.KEY)
          .setLifespan(1.days.inWholeMilliseconds)
          .setMaxAttempts(Parameters.UNLIMITED)
          .build()
      )
    }
  }

  override fun serialize(): ByteArray? {
    return ParticipantDeleteSendJobData(
      messageId = messageId,
      requestId = requestId,
      recipientIds = recipientIds,
      initialRecipientCount = initialRecipientCount
    ).encode()
  }

  override fun getFactoryKey(): String = KEY

  override fun run(): Result {
    if (!SignalStore.account.isRegistered) {
      Log.w(TAG, "Not registered. Skipping.")
      return Result.failure()
    }

    val message = SignalDatabase.messages.getMessageRecordOrNull(messageId)
    if (message == null) {
      Log.w(TAG, "Message vanished, aborting.")
      return Result.failure()
    }

    val conversationRecipientId = SignalDatabase.threads.getRecipientIdForThreadId(message.threadId)
    if (conversationRecipientId == null) {
      Log.w(TAG, "Thread recipient missing, aborting.")
      return Result.failure()
    }

    val conversationRecipient = SignalDatabase.recipients.getRecord(conversationRecipientId)
    val groupId = conversationRecipient.groupId

    val (scope: Int, groupRevision: Int?) = if (groupId != null && groupId.isV2) {
      val record = SignalDatabase.groups.getGroup(groupId)
      if (record.isEmpty) {
        Log.w(TAG, "Group record missing, aborting.")
        return Result.failure()
      }
      if (record.get().isTerminated) {
        Log.w(TAG, "Group terminated, aborting.")
        return Result.failure()
      }
      ParticipantDeleteConfig.SCOPE_GROUP_ALL_CURRENT_MEMBERS to record.get().requireV2GroupProperties().revision
    } else {
      ParticipantDeleteConfig.SCOPE_DIRECT_CHAT_BOTH_ACCOUNTS to null
    }

    val targetSentTimestamp = message.dateSent
    val targetAuthor = message.fromRecipient.requireServiceId()

    // Build the proto message body
    val participantDelete = SignalServiceDataMessage.ParticipantDelete(
      version = ParticipantDeleteConfig.PROTOCOL_VERSION,
      targetAuthor = targetAuthor,
      targetSentTimestamp = targetSentTimestamp,
      requestId = requestId,
      clientRequestedAt = System.currentTimeMillis(),
      scope = scope,
      groupRevision = groupRevision
    )

    val builder = newBuilder()
      .withTimestamp(System.currentTimeMillis())
      .withParticipantDelete(participantDelete)

    if (groupId != null && groupId.isV2) {
      GroupUtil.setDataMessageGroupContext(org.thoughtcrime.securesms.ApplicationContext.getInstance(), builder, groupId.requirePush())
    }

    val dataMessage = builder.build()

    // --- Deliver ---
    val existingNetworkFailures = message.networkFailures.toMutableSet()
    val existingIdentityMismatches = message.identityKeyMismatches.toMutableSet()

    val targets = (recipientIds +
      existingIdentityMismatches.map { it.recipientId.toLong() } +
      existingNetworkFailures.map { it.recipientId.toLong() }
      ).toSet()

    val recipients = targets.map { Recipient.resolved(RecipientId.from(it)) }.toMutableList()
    val eligible = RecipientUtil.getEligibleForSending(recipients.filter { it.hasServiceId })
    val ineligible = recipients - eligible

    // Dispatch via individual (direct chat) or bulk (group v2)
    val completed = mutableSetOf<RecipientId>()
    val unregistered = mutableListOf<Recipient>()
    val identityMismatch = mutableListOf<RecipientId>()
    val skipped = mutableListOf<Recipient>()

    if (groupId != null && groupId.isV2) {
      // Group v2: use bulk send
      val results = GroupSendUtil.sendResendableDataMessage(
        context = org.thoughtcrime.securesms.ApplicationContext.getInstance(),
        groupId = groupId.requireV2(),
        null,
        eligible.filterNot { it.isSelf },
        false,
        ContentHint.RESENDABLE,
        org.thoughtcrime.securesms.database.model.MessageId(messageId),
        dataMessage,
        true,
        false,
        null,
        null
      )
      for (result in results) {
        when (result) {
          is org.thoughtcrime.securesms.messages.GroupSendJobHelper.SendResult.Success -> completed.add(result.recipient.id)
          is org.thoughtcrime.securesms.messages.GroupSendJobHelper.SendResult.Unregistered -> unregistered.add(result.recipient)
          is org.thoughtcrime.securesms.messages.GroupSendJobHelper.SendResult.IdentityMismatch -> identityMismatch.add(result.recipient.id)
          is org.thoughtcrime.securesms.messages.GroupSendJobHelper.SendResult.Skipped -> skipped.add(result.recipient)
          is org.thoughtcrime.securesms.messages.GroupSendJobHelper.SendResult.Failure -> { /* network failure, tracked below */ }
        }
      }
      // sendSyncMessage for other devices on this account
      runCatching { AppDependencies.signalServiceMessageSender.sendSyncMessage(dataMessage) }
    } else {
      // Direct chat: one peer at a time
      for (r in eligible) {
        if (r.isSelf) {
          runCatching { AppDependencies.signalServiceMessageSender.sendSyncMessage(dataMessage) }
          continue
        }
        try {
          AppDependencies.signalServiceMessageSender.sendIndividualMessage(
            SignalServiceDataMessage.Companion.toContent(dataMessage),
            r.requireServiceId(),
            GroupUtil.DEFAULT_GROUPS_V2,
            emptyList()
          )
          completed.add(r.id)
        } catch (_: Exception) {
          // treated as network failure → will be retried by the job manager
        }
      }
    }

    // --- Update bookkeeping ---
    existingNetworkFailures.removeAll { completed.contains(it.recipientId) }
    existingIdentityMismatches.removeAll { completed.contains(it.recipientId) }

    val ineligibleIds = (ineligible.map { it.id } + unregistered.map { it.id }).toSet()
    existingNetworkFailures.removeAll { ineligibleIds.contains(it.recipientId) }
    existingIdentityMismatches.removeAll { ineligibleIds.contains(it.recipientId) }

    existingIdentityMismatches.addAll(identityMismatch)

    // Remove completed + permanently ineligible from our working list
    for (c in completed) recipientIds.remove(c.toLong())
    for (u in unregistered) {
      SignalDatabase.recipients.markUnregistered(u)
      recipientIds.remove(u.id.toLong())
    }
    for (inelig in ineligible) recipientIds.remove(inelig.id.toLong())

    SignalDatabase.messages.setNetworkFailures(messageId, existingNetworkFailures)
    SignalDatabase.messages.setMismatchedIdentities(messageId, existingIdentityMismatches)

    Log.i(TAG, "Completed now: ${completed.size} Skipped: ${ineligible.size + skipped.size} Remaining: ${recipientIds.size}")

    return if (existingNetworkFailures.isEmpty() && existingIdentityMismatches.isEmpty() && recipientIds.isEmpty()) {
      Result.success()
    } else if (existingIdentityMismatches.isNotEmpty()) {
      Log.w(TAG, "Identity mismatches (${existingIdentityMismatches.size}) — failing so user can resolve.")
      Result.failure()
    } else {
      Log.w(TAG, "Still need to reach ${recipientIds.size} recipient(s). Retrying.")
      Result.retry(defaultBackoff())
    }
  }

  override fun onFailure() {
    Log.w(TAG, "Participant delete send failed. ${initialRecipientCount - recipientIds.size}/$initialRecipientCount reached.")
    // Unlike admin-delete we do NOT have a "mark as failed" state in the messages table —
    // participant-delete failures are tracked in the Manager's request/pending rows and
    // retried by this Job's own retry loop. Nothing more to do here.
  }

  class Factory : Job.Factory<ParticipantDeleteSendJob> {
    override fun create(parameters: Parameters, serializedData: ByteArray?): ParticipantDeleteSendJob {
      val data = ParticipantDeleteSendJobData.ADAPTER.decode(serializedData!!)
      return ParticipantDeleteSendJob(
        messageId = data.messageId,
        requestId = data.requestId,
        recipientIds = data.recipientIds.toMutableList(),
        initialRecipientCount = data.initialRecipientCount,
        parameters = parameters
      )
    }
  }
}
